project:
  name: main-stack-test
  regions:
    - us-east-1
  template: templates/main.yaml
tests:
  main-stack-test:
    template: templates/main.yaml
    regions:
      - us-east-1
    tags:
      Project: group20-taskcat-test