version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade --force-reinstall cfn-lint==0.35.0 pyrsistent==0.16.0
      - pip install taskcat

  pre_build:
    commands:
      - echo "Running cfn-lint to validate CloudFormation templates..."
      - cfn-lint --ignore-checks W3687 --template templates/vpc.yaml
      - cfn-lint --ignore-checks W3687 --template templates/nat-gateway.yaml
      - cfn-lint --ignore-checks W3687 --template templates/route-tables.yaml
      - cfn-lint --ignore-checks W3687 --template templates/ec2.yaml
      - cfn-lint --ignore-checks W3687 --template templates/main.yaml

  build:
    commands:
      # - echo "Destroy the stack if it exists..."
      # - ./scripts/destroy.sh

      - echo "Running taskcat to test CloudFormation templates..."
      - ./scripts/upload_templates_to_s3.sh
      - taskcat test run

      # - echo "Deploying the stack..."
      # - ./scripts/deploy.sh


artifacts:
  files:
    - '**/*'