AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://group20-testing-bucket.s3.us-east-1.amazonaws.com/templates/vpc.yaml

  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://group20-testing-bucket.s3.us-east-1.amazonaws.com/templates/nat-gateway.yaml
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId

  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://group20-testing-bucket.s3.us-east-1.amazonaws.com/templates/route-tables.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        NatGatewayId: !GetAtt NatGatewayStack.Outputs.NatGatewayId

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://group20-testing-bucket.s3.us-east-1.amazonaws.com/templates/ec2.yaml
      Parameters:
        VPCId: !GetAtt VPCStack.Outputs.VPCId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnetId
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnetId
    