AWSTemplateFormatVersion: 2010-09-09
Description: Create NAT Gateway

Parameters: 
  PublicSubnetId:
    Type: String

Resources: 
  EIPForNAT:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
      - Key: Name
        Value: "Group-20-NAT-EIP"
  
  NatGateway: 
    Type: AWS::EC2::NatGateway  
    Properties:
      AllocationId: !GetAtt EIPForNAT.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: "Group-20-NAT-Gateway"
Outputs:
  NatGatewayId:
    Value: !Ref NatGateway